version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - java -jar target/kibana-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - target/kibana-0.0.1-SNAPSHOT.jar