server:
  port:
    8082

spring:
  main:
    web-application-type:NONE

kibana_url_source:
  local_local

kibana:
  url:
    source:
      http://_localhost:8090/api/saved_objects/_export
    dest:
      http://_localhost:8080/api/saved_objects/_import